---
title: "T-cell survival: CD4/CD8"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```

```{r}
meta <- read_tsv("../data/cellpop/cd48/metadata.txt")

data <- meta %>%
  group_by(day, cell.type, donor) %>%
  group_modify(~read_tsv(paste0("../data/cellpop/cd48/", .x$file.name))) %>%
  ungroup
```

```{r}
data.subset <- data %>%
  filter(day == "graft") %>%
  group_by(donor, cell.type, nSeqCDR3) %>%
  summarise(count = sum(cloneCount)) %>%
  mutate(quantile = case_when(
    count == 1 ~ "Singleton",
    count == 2 ~ "Doubleton",
    T ~ "Large"
  )) %>%
  mutate(quantile = factor(quantile,
                           c("Singleton", 
                             "Doubleton", 
                             "Large"))) %>%
  select(donor, cell.type, nSeqCDR3, quantile)
```

```{r}
data.survival <- data %>%
  filter(day != "graft") %>%
  select(day, donor, nSeqCDR3) %>%
  unique %>%
  inner_join(data.subset)
```

```{r}
data.survival.s <- data.survival %>%
  group_by(day, donor, cell.type, quantile) %>%
  summarise(alpha = n()) %>%
  ungroup %>%
  left_join(data.subset %>%
              group_by(donor, cell.type, quantile) %>%
              summarise(clones.pre = n()) %>% ungroup) %>%
  mutate(beta = clones.pre - alpha) %>%
  left_join(data %>%
              group_by(day, donor) %>%
              summarise(clones.post = length(unique(nSeqCDR3)))) %>%
  mutate(prob = alpha / (alpha + beta))
```

```{r fig.width=8, fig.height=4}
p3 <- data.survival.s %>%
  ggplot(aes(x = clones.post / clones.pre,
             y = alpha / (alpha + beta), 
             group = quantile, 
             color = quantile)) +
  geom_point(data = data.survival.s %>% select(-day, -cell.type),
             color = "grey", size = 5) +
  geom_point(size = 5) +
  geom_smooth(method = "lm", size = 1) +
  geom_text(aes(label = donor), size = 2, color = "black") +
  scale_x_log10("Clonotypes in recepient / clonotypes in donor",
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 3),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) + 
  scale_y_log10("Capture probability") +
  scale_color_manual("Quantile", values = c("#d7191c", "#fdae61", "#2b83ba")) +
  annotation_logticks(sides = "lb") +
  facet_grid(day ~ cell.type) +
  theme_classic() +
  theme(strip.background = element_blank(),
        legend.position = "bottom", legend.box="vertical")
p3

ggsave("../figures/fig6C.pdf")
```

```{r}
mdl <- lm(LogRecaptureProb ~ Quantile + LogDiversityRatio + day + cell.type,
          data.survival.s %>%
            mutate(LogRecaptureProb = log10(alpha / (alpha + beta)),
                   LogDiversityRatio = log10(clones.post / clones.pre),
                   Quantile = quantile))
summary(mdl)
```

```{r}
```


