---
title: "T-cell survival: DLI"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

library(tidyverse)
library(ggplot2)
library(reshape2)
library(ggridges)
library(broom)
library(scales)
library(forcats)
library(gridExtra)
library(cowplot)
```

# Load data
```{r message = F}
data <- tibble(fname = list.files("../data/hsct/")) %>%
  mutate(donor = startsWith(fname, "don"), 
         DLI = !(startsWith(fname, "don.sh.p") | startsWith(fname, "rec.sh.p")),
         sample.id = substr(fname, 5, nchar(fname))) %>%
  mutate(sample.id = paste0("D", sample.id %>% as.factor %>% as.integer, 
                            ifelse(DLI, "*", ""))) %>%
  group_by(donor, DLI, sample.id, fname) %>%
  group_modify(~read_tsv(paste0("../data/hsct/", .y$fname))) %>%
  ungroup %>%
  select(-fname)
```

```{r}
data %>%
  filter(donor) %>%
  select(sample.id, DLI) %>%
  unique
```

# Merge data
```{r}
data.m <- full_join(data %>%
                      filter(donor) %>%
                      mutate(count.don = count) %>%
                      select(-donor, -count),
                    data %>%
                      filter(!donor) %>% 
                      mutate(count.rec = count) %>%
                      select(-donor, -count)) %>%
  mutate(quantile.don = case_when(
    is.na(count.don) ~ "Novel",
    count.don == 1 ~ "Singleton",
    count.don == 2 ~ "Doubleton",
    count.don == 3 ~ "Tripleton",
    T ~ "Large"
  ),
  quantile.rec = case_when(
    is.na(count.rec) ~ "Missing",
    count.rec == 1 ~ "Singleton",
    count.rec == 2 ~ "Doubleton",
    count.rec == 3 ~ "Tripleton",
    T ~ "Large"
  )) %>%
  mutate(quantile.don = factor(quantile.don,
                               c("Novel", "Singleton", 
                                 "Doubleton", "Tripleton",
                                 "Large")),
         quantile.rec = factor(quantile.rec,
                               c("Missing", "Singleton", 
                                 "Doubleton", "Tripleton",
                                 "Large")))

data.m <- data.m %>%
  left_join(data %>%
              group_by(sample.id, donor) %>%
              summarise(total = length(unique((paste(v, cdr3nt))))) %>%
              group_by(sample.id) %>%
              summarise(total.don = total[donor],
                        total.rec = total[!donor]))
```

```{r}
p1 <- data.m %>%
  filter(!DLI) %>%
  ggplot(aes(x = sample.id %>% fct_reorder(total.rec), 
             group = quantile.don,
             fill = quantile.don)) +
  geom_bar(position = "dodge") +
  scale_y_log10("Unique clonotypes", limits = c(1, 1e6),
                expand = c(0,0),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  xlab("Donor-recipient pair") +
  scale_fill_manual("Size in Donor", 
                    values = c("grey", "#d7191c", "#fdae61",
                               "#abdda4", "#2b83ba")) +
  annotation_logticks(sides = "l") +
  theme_classic() +
  theme(legend.position = "bottom")
p1

p2 <- data.m %>%
  filter(!DLI) %>%
  ggplot(aes(x = sample.id %>% fct_reorder(total.rec), 
             group = quantile.rec,
             fill = quantile.rec)) +
  geom_bar(position = "dodge") +
  scale_y_log10("Unique clonotypes", limits = c(1, 1e6),
                expand = c(0,0),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  xlab("Donor-recipient pair") +
  scale_fill_manual("Size in Recepient", 
                    values = c("grey", "#d7191c", "#fdae61",
                               "#abdda4", "#2b83ba")) +
  annotation_logticks(sides = "l") +
  theme_classic() +
  theme(legend.position = "bottom")
p2
```
# Capture probability calculation
```{r}
alpha.prior <- 1
beta.prior <- 1

data.s <- data.m %>%
  group_by(DLI,
           sample.id, quantile.don, 
           total.don, total.rec) %>%
  summarise(alpha = sum(quantile.rec != "Missing") + alpha.prior,
            beta = sum(quantile.rec == "Missing") + beta.prior)

data.b <- data.s %>%
  merge(tibble(p = c(0:1000/1000, 10^(-4000:-1000/1000)))) %>%
  group_by(sample.id, quantile.don) %>%
  mutate(Pbeta = dbeta(p, alpha, beta)) %>%
  ungroup

p3 <- data.b %>%
  filter(quantile.don != "Novel", !DLI) %>%
  group_by(sample.id) %>%
  mutate(height = Pbeta / max(Pbeta)) %>%
  ggplot(aes(x = p, y = sample.id, height = height, 
             fill = quantile.don)) +
  geom_ridgeline(color = NA, alpha = 0.9) + 
  scale_x_log10("Capture probability", 
                limits = c(1e-4, 0.1),
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 4),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) + ylab("Beta distribution density") +
  scale_fill_brewer(guide = F, palette = "Spectral") +
  annotation_logticks(sides = "b") +
  theme_classic() +
  theme(legend.position = "bottom")
p3
```

```{r}
p4 <- data.s %>%
  filter(quantile.don != "Novel", !DLI) %>%
  ggplot(aes(x = total.rec / total.don,
             y = alpha / (alpha + beta), 
             group = quantile.don, 
             color = quantile.don)) +
  geom_smooth(method = "lm", aes(), size = 1) +
  geom_point(size = 5) +
  geom_text(aes(label = sample.id), size = 2, color = "white") +
  scale_x_log10("Clonotypes in recepient / clonotypes in donor",
                limits = c(1e-2, 5),
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 3),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) + 
  scale_y_log10("Capture probability estimate",
                limits = c(1e-4, 1e-1),
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 4),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  scale_color_brewer(guide = F, "", palette = "Spectral") +
  annotation_logticks(sides = "lb") +
  theme_classic() +
  theme(legend.position = "bottom")
p4
```
# Linear model
```{r}
mdl <- lm(LogRecaptureProb ~ Quantile + LogDiversityRatio,
          data.s %>%
            filter(quantile.don != "Novel", !DLI) %>%
            mutate(LogRecaptureProb = log10(alpha / (alpha + beta)),
                   LogDiversityRatio = log10(total.rec / total.don),
                   Quantile = quantile.don))
summary(mdl)

tbl <- mdl %>%
  tidy %>%
  mutate(estimate = signif(estimate, 2),
         std.error = signif(std.error, 1),
         p.value = format(signif(p.value, digits = 1), scientific = T)) %>%
  select(term, estimate, std.error, p.value)

knitr::kable(tbl)

# p4 +
#   annotate(geom = "text", x = 0.1, y = 0.5,
#            label = summary(mdl)$r.squared) +
#   annotation_custom(tableGrob(tbl, 
#                               rows = NULL,
#                               theme = ttheme_minimal(base_size=4,
#                                                      padding = unit(c(1, 1),
#                                                                     "mm"))),
#                     xmin=-0.5, ymin = -5.7) -> p5
# p5
```

```{r fig.width=10, fig.height=8}
plot_grid(p1 +  
            theme(legend.title = element_text(size = 8), 
                  legend.text = element_text(size = 7)),
          p2 +  
            theme(legend.title = element_text(size = 8), 
                  legend.text = element_text(size = 7)), 
          p3, p4, 
          labels = c("A", "B", "C", "D"),
          label_size = 12) -> fig2
fig2
ggsave("../figures/fig2.pdf", fig2)
```

Check for difference between DLI and non-DLI using our model

```{r}
mdl2 <- lm(LogRecaptureProb ~ Quantile + LogDiversityRatio + DLI,
          data.s %>%
            filter(quantile.don != "Novel") %>%
            mutate(LogRecaptureProb = log10(alpha / (alpha + beta)),
                   LogDiversityRatio = log10(total.rec / total.don),
                   Quantile = quantile.don))
summary(mdl2)

tbl2 <- mdl2 %>%
  tidy %>%
  mutate(estimate = signif(estimate, 1),
         std.error = signif(std.error, 1),
         p.value = signif(p.value, 1)) %>%
  select(term, estimate, std.error, p.value)

knitr::kable(tbl2)

p5 <- data.s %>%
  filter(quantile.don != "Novel") %>%
  ggplot(aes(x = total.rec / total.don,
             y = alpha / (alpha + beta), 
             group = quantile.don, 
             color = quantile.don,
             shape = DLI,
             linetype = DLI)) +
  geom_smooth(method = "lm",
              aes(group = paste(quantile.don, DLI)), size = 1) +
  geom_point(size = 5) +
  geom_text(aes(label = sample.id), size = 2, color = "black") +
  scale_x_log10("Clones in recepient / clones in donor") + 
  scale_y_log10("Capture probability") +
  scale_linetype_manual("DLI", values = c("dotted", "solid")) +
  scale_color_brewer("Quantile", palette = "Spectral") +
  scale_shape_manual("DLI", values = c(1, 16)) +
  annotation_logticks(sides = "lb") +
  theme_classic() +
  theme(legend.position = "bottom", legend.box="vertical")
p5
```

Conventional way - correlation of log counts

```{r}
data.m %>%
  filter(!is.na(count.don), !is.na(count.rec)) %>%
  group_by(DLI, sample.id) %>%
  group_modify(~cor.test(log10(.x$count.don), 
                         log10(.x$count.rec)) %>% tidy) -> data.cor

knitr::kable(data.cor)

p6 <- data.m %>%
  filter(!is.na(count.don), !is.na(count.rec)) %>%
  ggplot(aes(x = count.don, y = count.rec)) +
  #geom_point(alpha = 0.5, aes(color = quantile.don)) +
  #geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  geom_point(aes(color = DLI)) +
  geom_text(data = data.cor %>%
              mutate(text = paste0("R2=", round(estimate^2, 3),
                                   "\nP=", signif(p.value,1))) %>%
              select(sample.id, text),
            aes(label = text, x = 1000, y = 100000)) +
  geom_smooth(method = "lm", color = "black") +
  scale_x_log10("Count in donor", limits = c(1, 1e6),
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 4),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  scale_y_log10("Count in receptient", limits = c(1, 1e6), 
                breaks = scales::trans_breaks("log10", function(x) 10^x, n = 4),
                labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(sides = "lb", size = 0.2) +
  scale_color_brewer(palette = "Set1", guide = F) +
  facet_wrap(. ~ sample.id) +
  theme_classic() +
  theme(strip.background = element_blank())
p6
```

```{r fig.width=11, fig.height=6}
plot_grid(p5, p6, 
          labels = c("A", "B"),
          rel_widths = c(1, 1.3)) -> fig5
fig5
ggsave("../figures/fig5.pdf", fig5)
```

```{r}

```
