---
title: "T-cell survival: 3 year dynamic and YF data"
date: '2022-10-12'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(forcats)
library(stringr)
library(scales)
library(cowplot)
```

### Aging data

```{r}
meta.a <- read_tsv("../data/aging_3year/metadata.txt")
meta.a
```

```{r}
data.a <- meta.a %>%
  group_by(donor, age) %>%
  group_modify(~read_tsv(paste0("../data/aging_3year/", .x$file.name))) %>%
  ungroup %>%
  mutate(tcrkey = paste(v, cdr3nt)) %>%
  group_by(donor, age, tcrkey) %>%
  summarise(count = sum(count)) %>%
  ungroup
```

```{r}
data.a %>%
  group_by(donor, age) %>%
  summarise(diversity = length(unique(tcrkey)))
```

```{r}
data.a.m <- data.a %>%
  filter(age %in% c(27, 47)) %>%
  left_join(data.a %>% 
          filter(age %in% c(30, 50)) %>%
          select(donor, tcrkey) %>%
          unique %>%
          mutate(overlapping = T)) %>%
  mutate(overlapping = !is.na(overlapping))
```

```{r}
data.a.s <- data.a.m %>%
  mutate(count = pmin(10, count)) %>%
  group_by(sample = paste0(donor, " ", age, "yo"), count) %>%
  summarise(alpha = sum(overlapping), 
            beta = sum(!overlapping))
```

```{r}
p1 <- data.a.s %>%
  ggplot(aes(x = count, y = alpha / (alpha + beta),
             color = sample, group = )) +
  geom_point(aes(x = as.factor(
    ifelse(count > 9, "10+", count) %>%
      fct_reorder(count)
    ), shape = count > 9)) +
  geom_smooth(data = data.a.s %>% filter(count < 10),
              method = "lm") +
  scale_color_brewer("", palette = "Set1") +
  scale_y_log10("Capture probability") +
  scale_shape(guide = F) +
  xlab("Count at first time point") +
  theme_classic() +
  annotation_logticks(sides = "l") +
  theme(legend.position = "bottom")
p1
```

```{r}
mdl <- lm(LogRecaptureProb ~ count + sample,
          data.a.s %>%
            filter(count < 9) %>%
            mutate(LogRecaptureProb = log10(alpha / (alpha + beta))))
summary(mdl)
```

Estimating clonotype size. The re-capture probability is $P = 1 - e^{-fR}$, so $f = -ln(1-P)/R$ where $R\sim10^6$ number of reads

```{r}
data.a.s %>%
  group_by(sample) %>%
  mutate(total = sum(count * (alpha + beta)),
         weight = count * (alpha + beta) / total) %>%
  mutate(P = alpha / (alpha + beta),
         f = -log(1-P) / total,
         fmean = sum(weight * f),
         cells = fmean * 1e11)
```

### Yellow fever data

```{r message=FALSE}
meta.v <- read_tsv("../data/yellow_fever_vac/metadata.txt") %>%
  filter(time %in% c(-1 , 0))

data.v <- meta.v %>%
  filter(replica == "F1") %>%
  group_by(donor, time, replica) %>%
  group_modify(~ read_tsv(paste0("../data/yellow_fever_vac/", .x$file.name))) %>%
  mutate(cdr3 = cdr3nt) %>%
  group_by(donor, time, replica, cdr3, v) %>%
  summarise(count = sum(count)) %>%
  ungroup
```

```{r}
data.v <- data.v %>%
  mutate(quantile = case_when(
    count == 1 ~ "Singleton",
    count == 2 ~ "Doubleton",
    count == 3 ~ "Tripleton",
    T ~ "Large"
  )) %>%
  mutate(quantile = factor(quantile,
                           c("Singleton", 
                             "Doubleton", "Tripleton",
                             "Large"))) %>%
  select(-count)
  
data.v.m <- left_join(
  data.v %>%
    filter(time == -1)  %>%
    select(-time, -replica),
  data.v %>%
    filter(time == 0) %>%
    mutate(found = T) %>%
    select(-quantile, -time, -replica),
  by = c("donor", "cdr3", "v")
) %>%
  mutate(found = !is.na(found))
```

```{r}
data.v.s <- data.v.m %>%
  group_by(donor, quantile) %>%
  summarise(alpha = sum(found),
            beta = sum(!found)) %>%
  left_join(data.v %>%
              filter(time == -1) %>%
              group_by(donor) %>%
              summarise(clonotypes.pre = length(unique(paste(v, cdr3)))))%>%
  left_join(data.v %>%
              filter(time == 0) %>%
              group_by(donor) %>%
              summarise(clonotypes.post = length(unique(paste(v, cdr3)))))
```

```{r}
p2 <- data.v.s %>%
  ggplot(aes(x = clonotypes.post / clonotypes.pre,
             y = alpha / (alpha + beta), 
             group = quantile, 
             color = quantile)) +
  geom_smooth(method = "lm", aes(), size = 1) +
  geom_point(size = 5) +
  geom_text(aes(label = donor), size = 2, color = "white") +
  scale_x_log10("Clones at d0 / clones at d-7") + 
  scale_y_log10("Capture probability") +
  scale_color_brewer("Size at d0", palette = "Spectral") +
  annotation_logticks(sides = "l") +
  theme_classic() +
  theme(legend.position = "bottom")
p2
```

```{r}
mdl <- lm(LogRecaptureProb ~ Quantile + LogDiversityRatio,
          data.v.s %>%
            mutate(LogRecaptureProb = log10(alpha / (alpha + beta)),
                   LogDiversityRatio = log10(clonotypes.post / clonotypes.pre),
                   Quantile = quantile))
summary(mdl)
```

```{r fig.width=8, fig.height=4}
plot_grid(p1 +  
            theme(legend.title = element_text(size = 8), 
                  legend.text = element_text(size = 7)), 
          p2 +  
            theme(legend.title = element_text(size = 8), 
                  legend.text = element_text(size = 7)),
          labels = c("A", "B"),
          label_size = 10) -> fig3
fig3
ggsave("../figures/fig3.pdf", fig3)
```


```{r}
#E
```